-- Identity ------------------------------------------------------------------
CREATE TABLE users (
    id              UUID PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    full_name       VARCHAR(200) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    area            VARCHAR(200),
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE roles (
    code        VARCHAR(40) PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE permissions (
    code        VARCHAR(60) PRIMARY KEY,
    description VARCHAR(500)
);

CREATE TABLE role_permissions (
    role_code       VARCHAR(40) NOT NULL REFERENCES roles (code),
    permission_code VARCHAR(60) NOT NULL REFERENCES permissions (code),
    PRIMARY KEY (role_code, permission_code)
);

CREATE TABLE user_roles (
    user_id   UUID        NOT NULL REFERENCES users (id),
    role_code VARCHAR(40) NOT NULL REFERENCES roles (code),
    PRIMARY KEY (user_id, role_code)
);

-- Project -------------------------------------------------------------------
CREATE TABLE projects (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(40)  NOT NULL UNIQUE,
    name              VARCHAR(200) NOT NULL,
    description       VARCHAR(2000),
    color             VARCHAR(7)   NOT NULL,
    icon              VARCHAR(60),
    owner_id          UUID REFERENCES users (id),
    pmo_id            UUID REFERENCES users (id),
    jira_project_key  VARCHAR(40),
    gitlab_project_id VARCHAR(100),
    active            BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Workflow ------------------------------------------------------------------
CREATE TABLE workflow_definitions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(40)  NOT NULL UNIQUE,
    name        VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    active      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE workflow_stages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id       BIGINT       NOT NULL REFERENCES workflow_definitions (id),
    code              VARCHAR(60)  NOT NULL,
    name              VARCHAR(200) NOT NULL,
    category          VARCHAR(30)  NOT NULL,
    position          INT          NOT NULL,
    auto_advance      BOOLEAN      NOT NULL DEFAULT FALSE,
    jira_status       VARCHAR(100),
    on_enter_actions  VARCHAR(500),
    exit_requirements VARCHAR(500),
    CONSTRAINT uq_stage_code UNIQUE (workflow_id, code)
);

CREATE TABLE workflow_transitions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id         BIGINT       NOT NULL REFERENCES workflow_definitions (id),
    from_stage_id       BIGINT       NOT NULL REFERENCES workflow_stages (id),
    to_stage_id         BIGINT       NOT NULL REFERENCES workflow_stages (id),
    action              VARCHAR(60)  NOT NULL,
    label               VARCHAR(200) NOT NULL,
    required_permission VARCHAR(60),
    requires_reason     BOOLEAN NOT NULL DEFAULT FALSE,
    forward             BOOLEAN NOT NULL DEFAULT FALSE,
    system_only         BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_transition UNIQUE (from_stage_id, action)
);

CREATE TABLE approval_rules (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id        BIGINT       NOT NULL REFERENCES workflow_definitions (id),
    stage_code         VARCHAR(60)  NOT NULL,
    name               VARCHAR(200) NOT NULL,
    approver_role      VARCHAR(40)  NOT NULL REFERENCES roles (code),
    condition_field    VARCHAR(60),
    condition_operator VARCHAR(10),
    condition_value    VARCHAR(500),
    project_id         BIGINT REFERENCES projects (id),
    active             BOOLEAN NOT NULL DEFAULT TRUE,
    position           INT     NOT NULL DEFAULT 0
);

-- Catalog -------------------------------------------------------------------
CREATE TABLE demand_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(40)  NOT NULL UNIQUE,
    name        VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    technical   BOOLEAN NOT NULL DEFAULT FALSE,
    workflow_id BIGINT  NOT NULL REFERENCES workflow_definitions (id),
    active      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE priorities (
    code        VARCHAR(10) PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    rank_order  INT          NOT NULL,
    color       VARCHAR(7)   NOT NULL,
    policy      VARCHAR(1000)
);

CREATE TABLE execution_statuses (
    code                  VARCHAR(40) PRIMARY KEY,
    name                  VARCHAR(100) NOT NULL,
    position              INT          NOT NULL,
    gitlab_label          VARCHAR(100) NOT NULL,
    done                  BOOLEAN      NOT NULL DEFAULT FALSE,
    jira_comment_template VARCHAR(1000) NOT NULL
);
